packages:
  - apps/*
  - packages/*

catalog:
  '@astrojs/check': ^0.9.4
  '@astrojs/mdx': ^4.3.0
  '@astrojs/react': ^4.3.0
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.29.0
  '@eslint/markdown': ^6.6.0
  '@logux/eslint-config': ^55.2.1
  '@next/eslint-plugin-next': ^15.3.4
  '@tailwindcss/cli': ^4.1.11
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/typography': ^0.5.16
  '@tailwindcss/vite': ^4.1.11
  '@types/canvas-confetti': ^1.9.0
  '@types/node': ^24.0.4
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@vitejs/plugin-react': ^4.6.0
  astro: ^5.10.1
  astro-eslint-parser: ^1.2.2
  canvas-confetti: ^1.9.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  daisyui: ^5.0.43
  eslint: ^9.29.0
  eslint-config-next: ^15.3.4
  eslint-config-prettier: ^10.1.5
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.4
  globals: ^16.2.0
  next: ^15.3.4
  postcss: ^8.5.6
  prettier: ^3.6.2
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.6.13
  react: ^19.1.0
  react-dom: ^19.1.0
  react-icons: ^5.5.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
  tsup: ^8.5.0
  typescript-eslint: ^8.35.0
  vite: ^6.3.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
