packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
catalog:
  "@astrojs/mdx": ^4.2.3
  "@astrojs/react": ^4.2.3
  "@eslint/eslintrc": ^3.3.1
  "@eslint/js": ^9.24.0
  "@eslint/markdown": ^6.3.0
  "@logux/eslint-config": ^55.2.0
  "@next/eslint-plugin-next": ^15.2.4
  "@tailwindcss/cli": ^4.1.3
  "@tailwindcss/postcss": ^4.1.3
  "@tailwindcss/typography": ^0.5.16
  "@tailwindcss/vite": ^4.1.3
  "@types/canvas-confetti": ^1.9.0
  "@types/node": ^22.14.0
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.1
  "@vercel/style-guide": ^6.0.0
  astro: ^5.6.1
  astro-eslint-parser: ^1.2.2
  canvas-confetti: ^1.9.3
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.24.0
  eslint-config-next: 15.2.4
  eslint-config-prettier: ^10.1.1
  eslint-plugin-astro: ^1.3.1
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.0
  globals: ^16.0.0
  postcss: ^8.5.3
  prettier: ^3.5.3
  prettier-plugin-astro: ^0.14.1
  prettier-plugin-tailwindcss: ^0.6.11
  react: ^19.1.0
  react-dom: ^19.1.0
  react-icons: ^5.5.0
  tailwind-merge: ^3.2.0
  tailwindcss: ^4.1.3
  turbo: ^2.5.0
  typescript: ^5.8.3
  typescript-eslint: ^8.29.1
